# Site settings
title: Comment venir au laboratoire de mathématiques Paul Painlevé de Lille
email: marc.pegon@univ-lille.fr
url: "https://pegonma.github.io" # the base hostname & protocol for your site
github:
  user : pegonma
  branch: gh-pages
baseurl: "/venir-labopp/" # the subpath of your site, e.g. /blog/
address: > #   L'adresse du laboratoire
  bâtiment M2<br>
  Cité Scientifique<br>
  59650 Villeneuve-d'Ascq
gps: ["50.609","3.138"]

# libraries
jqueryurl: "https://code.jquery.com/" # the path to jQuery

# Build settings
permalink: pretty
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: true
  auto_ids: false

exclude:
  - Work

theme: jekyll-theme-minimal
