# Site settings
title: Comment venir à Polytech Lille
email: marc.pegon@univ-lille.fr
url: "https://pegonma.github.io" # the base hostname & protocol for your site
github:
  user : pegonma
  branch: gh-pages
baseurl: "/venir-polytech/" # the subpath of your site, e.g. /blog/
address: > #   L'adresse de Polytech Lille
  Polytech Lille<br>
  Cité Scientifique<br>
  Avenue Paul Langevin<br>
  59650 Villeneuve-d'Ascq
gps: ["50.60786092986147", "3.1365825353448193"]

# libraries
jqueryurl: "https://code.jquery.com/" # the path to jQuery

# Build settings
permalink: pretty
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: true
  auto_ids: false

exclude:
  - Work

theme: jekyll-theme-minimal
